### ISSUE TITLE
Run in parallel?

### ISSUE THREAD

**Issue by roryc89** [natefaubion/purescript-run#17]
We have a blocks of program we would like to run in parallel. Is there any way to perform this  sort of logic with purescript-run? 

I.e.: 
```purs

handlerProgram :: forall effs.  A -> Run effs Result
handlerProgram a = do
   var1 <- sequentialAsyncEffect a -- sequential 

   {var2, var3} <- {var2:_, var3:_} -- parallel
      <$> parallelAsyncEffect1 var1
      <*> parallelAsyncEffect2 var1

   traversePar doSomethingElseParallel var3 -- also parallel
   ...
```

Any help would be greatly appreciated. So far we have only been able to interpret the program sequentially.

**Comment by natefaubion** [comment]
It's not possible to have blocks of parallel code like that _in general_ because `Run` is open-world, and not all effects can be run in parallel and then _joined_. It's possible to `fork` (that's essentially what `CHOICE` gives you), but then resuming from a single point after some set of effects have completed always requires consideration. For example, if you run multiple `STATE` effects in parallel, how do you join the results? You might have to require a commutative Monoid for the state type then for it to make sense. Likewise with `EXCEPT`, how do you recover if one of your forks (or all of them) throws? Do you collect errors, discard errors, etc? You have to handle each case specifically according to the semantics you want, and there's no possible one-size-fits-all solution.

One option is to define a closed-world set of effects that are known to run in parallel with the semantics you want, and lift that into your `Run` effects.

```purescript
newtype MyParEffects a =
  MyParEffect (FreeAp (Run (...)) a)

liftParEffects :: forall r a. MyParEffects a -> Run (par :: FProxy MyParEffects | r) a
liftParEffects = Run.lift (SProxy :: SProxy "par")
```

Your interpreter can than interpret the `FreeAp` of all the embedded `Run` effects in parallel.

An alternative would be to have only `fork`ing as an effect, and then also have some sort of coordination primitive like `AVar`s to deal with joins.

**Comment by roryc89** [comment]
Thanks a lot! This is just what we were looking for. I assume this can be closed then?
